### ISSUE TITLE
plasma 5.8 compability

### ISSUE THREAD

**Issue by alexjp** [psifidotos/nowdock-plasmoid#39]
Hi,

Opening issues for things that work in plasma 5.7 but not in 5.8.

I saw this in debug mode of plasmashell, the dock still works but in plasmashell debug it complains:

```
file:///home/alex/.local/share/plasma/plasmoids/org.kde.store.nowdock.plasmoid/contents/ui/main.qml:807: Error: Function.prototype.connect: target is not a function
```

Thanks and congrats on the release :)

**Comment by psifidotos** [comment]
The specific line in used to create launchers from dropping them inside the plasmoid... I suppose you can not drop a launcher... :(

What I am going to do is the following... 
the version 0.3 which was published will keep the Plasma 5.7 compatibility, but version 0.4 will need Plasma 5.8..

until know what does not work in Plasma 5.8:

---
- **screen filtering (I commented just before the release)**
- **dropping a launcher from outside**
- **now dock panel is not appearing in the panel list**

**Comment by psifidotos** [comment]
Nice to hear from you @alexjp !! :) I hope you are fine!! Thank u for being so active!!! @kupiqu also of course !! and all of you guys that encourage me so much!!!

**Comment by kupiqu** [comment]
You are more than welcome, and congrats for this great release!

**Comment by psifidotos** [comment]
thank u @kupiqu ! More than tired actually in order for the release to happen... but a few days break will give me strength for the future developments.... ;) .... bug fixes!! and panel spacer support for Now Dock Panel 0.4!!! :)

**Comment by psifidotos** [comment]
Now Dock Panel is not appearing in the panel list even though it is installed correctly...
Well, there are some changes in plasma codepage... I must wait to see the final release to understand what has happened..

Contacting plasma developers, the reference is around **NoDisplay=true** and maybe providing an
**Empty Now Dock Panel** layout ...

**Comment by kupiqu** [comment]
To be fully compatible with plasma 5.8, the following would be a nice add too:

"Task manager gained further productivity features in this release. Media controls that were previously available in task manager tooltips only are now accessible in the context menus as well. In addition to bringing windows to the front during a drag and drop operation, dropping files onto task manager entries themselves will now open them in the associated application. Lastly, the popup for grouped windows can now be navigated using the keyboard and text rendering of its labels has been improved."

![plasma-5 8-media-controls](https://cloud.githubusercontent.com/assets/3875196/19090507/cfe60a76-8a4c-11e6-9a0e-c572dd476e19.png)

**Comment by psifidotos** [comment]
@kupiqu, I dont know... we will see... fully compatible does not mean supporting the same functionality... now dock is trying to be as simplistic as possible... we will see... anything that doesnt increase complexity and its important functionality it could be added but for the rest I dont know...

**Comment by kupiqu** [comment]
Ok, sounds good. I, for one, would like the option but I understand that this added to all the rest of features might be a bit too much. More so, if other users are not interested in this.

Thanks for the good work!

**Comment by psifidotos** [comment]
@kupiqu, there are 3 different features which one are you referring?:
1. media controls in pop up ( i dont think this is difficult)
2. dropping files onto task manager entries, opens them... (I cant understand the use of this... why the user not just click the file to open or right click it and open with?)
3. popup for grouped windows etc. (Now Dock plasmoid is not using pop up for the grouped windows, it uses only the present windows kwin effect)

**Comment by kupiqu** [comment]
I meant simply 1) above.
I find option 2 a bit silly too, but it may make some sense for very unfamiliar users to plasma and linux in general, i.e. users who don't know how to associate files with specific apps, so they can just drag'n'drop. I don't think you have to implement that.
Option 3, I don't really care much either, I like the nice windows preview that you added from plasma to the plasmoid :)

**Comment by MarianArlt** [comment]
> dropping files onto task manager entries, opens them... (I cant understand the use of this... why the user not just click the file to open or right click it and open with?)

As a decade long OSX dock user I can totally explain you that your associated program for a specific file type is NOT always (and actually quite often) the one you want to open that file with. I don't want to open something like Gimp any time I double click a .jpg but I most certainly want to edit some JPGs at some point of my digital life. Or even on a daily basis if it's for work.
The drag & drop approach makes this blazing fast (way more accessible than context menu and search for "Open with..." then search again the application in the sub menu...) and you can even change opinion about opening it with another of your favorite app (cause your dock apparently is just that) with very little downtime in UX.
Not pushing you or anything but this very behaviour is one I used most in 10 years of OSX.

Greetings and Kudos for your very nice widget (I still have to find out how to configure it correctly ;)

**Comment by psifidotos** [comment]
@kupiqu so I think (1) is in for 0.4, in 0.4 version I will also add a way to choose a window's activities which probably the default taskmanager already supports it in Plasma 5.8 . Big example of this are the new Gnome windows which have CSD (Client side decorations) and for them plasma does not draw a title bar, so the only way for the user to set the activities is through the task manager...

@MarianArlt , sounds interesting... :) we'll see... My big concern is that the plasmoid must distinguish dropping launchers from dropping files... if this is possible easily then I dont object.. :)

> (I still have to find out how to configure it correctly ;)

do you have any specific problem that we can help you with?

**Comment by kupiqu** [comment]
excellent

**Comment by MarianArlt** [comment]
@psifidotos I guess I entered in a still growing phase of everything. I'm on Plasma 5.8 now so I'll have to wait for your next release. Before that I had problems to understand the difference between your two widgets and how to get a simple dock with a few launchers set up instead of a task switcher of opened applications. Maybe someone could collaborate on a little documentation? Would probably be good publicity as well and in the end generate more collaboration?

I'll be patient. Thanks again for your efforts. Glad there's people like you :+1:

**Comment by psifidotos** [comment]
@MarianArlt thanks for the kind words... When Plasma 5.8 hit openSuse repos I am going to switch in order to start preparing 0.4. 

> I had problems to understand the difference between your two widgets and how to get a simple dock with a few launchers set up instead of a task switcher of opened applications

There are two widgets, Now Dock Plasmoid and Now Dock Panel,
the plasmoid (v0.3.2 currently) provides support for the open windows and for the launchers

the panel (v0.3.1 currently) provides support for extra plasmoids e.g. clocks, notes, calculators, weather widgets etc....

The plasmoid even in its current version(0.3.2) I think it can be installed directly in Plasma 5.8,
the issue is with the panel (not appearing in the panel's list but I think I have found and easy solution for this but I have to test it first)

I would suggest you to add first the plasmoid in the desktop and play with it(open windows, add launchers etc)...
When you have succeed in this then the next step would be how does that plasmoid gets into a panel and then the next small issues arise and can be answered.. 

The most common issues that the users had until now were:
1. How does Now Dock appear above the windows?
2. How does a panel become transparent but I keep my theme?
3. How can I make my clock and my weather widgets etc. animate on hover like your video? :)

all these are answered easily... :)

in plasma 5.8 with the current versions you could have 1 and 2 but not 3...

> Maybe someone could collaborate on a little documentation? Would probably be good publicity as well and in the end generate more collaboration?

I am definitely open if someone wants to try something, for example we could use the Wiki page in github, in order to answer the most common issues for users!! :) a small example it could be also the transparent panel how it can be achieved!! I can help of course in the review!

**Comment by kupiqu** [comment]
Indeed, I'm using nowdock panel and plasmoid in plasma 5.8 without problems. The issue I guess is to install the panel from scratch as it is not an option in plasma 5.8 (I had it from before, plasma 5.7)

> The plasmoid even in its current version(0.3.2) I think it can be installed directly in Plasma 5.8,
> the issue is with the panel (not appearing in the panel's list but I think I have found and easy solution for this but I have to test it first)

**Comment by psifidotos** [comment]
ok, let's summarize a bit what will need for **0.4** versions, please ping me if I forgot something...
1. media controls in pop up menu **(has already been implemented in master)**
2. screen filtering to be fixed
3. dropping a launcher(s) to add or file(s) on a launcher to open
4. **now dock panel** is not appearing in the panel list

I would like a lot your feedback for **(4)** please... 
**Situation for (4)**
**SOLUTIONS FOR (4):**
1. remove from **metadata.desktop** the reference **NoDisplay=true** this is going to show in the panel list the record "Empty Now Dock Panel" but the Now Dock Panel is also going to appear in plasma's widgets list in parallel with the Now Dock Plasmoid, **(maybe will that create a confusion? we could set different icons of course )**.
2. create a new **empty layout** for the panel but this is going to break the 1-click install from **kde store** because the user will have to go **only** for a **manual installation (command line)**

**Comment by kupiqu** [comment]
I would say option 1 is better

**Comment by MarianArlt** [comment]
I wouldn't say multiple options to add functionality is confusing at all. Actually that's pretty much the basics of any DE really. You have like 10 options to open/close/copy/move files and programs. It's just natural and some people will choose one way over another just as others the way round.
Just my humble opinion of course.
Kudos!

**Comment by psifidotos** [comment]
I am also fond for **option 1** which makes the maintenance easier...

**Comment by psifidotos** [comment]
Unfortunately **option 1** is not in the table...
We go only for **option 2 - manual installation for Now Dock Panel v0.4 in Plasma 5.8** 

The reason in the following... I sent it at the plasma developers...

> A small update for this for Plasma 5.8,
> removing "NoDisplay=true" from metadata.desktop is not an option for me... The panel is appearing in the widgets list but there is the following not acceptable behavior.
> If the user tries to add the Now Dock Panel from the widgets list then the panel is trying to be added in the desktop containment and that creates a plasma crash that can not be fixed if the user dont edit its plasma configuration files (so the user can not login to plasma at all after that).
> 
> That creates the following situation:
> 
> Now Dock Panel will be installed only through user manual installation and not from the 1-click install of store.kde.org which is disappointing actually. This is happening because I have to add a default and an empty layouts for the Now Dock Panel and these can not be installed from the same plasmoid package and correct me if I am wrong but layouts also can not be installed at all from 1-click install of store.kde.org
> 
> regards,
> 
> michail

**Comment by psifidotos** [comment]
I have just added the "Empty Now Dock Panel" in **master** branch in Now Dock Panel, from now on then panel **should NOT** be installed through **plasmapkg2** or directly from the **store.kde.org**. The user **should execute** one of the installation scripts provided by the Now Dock Panel

**Comment by psifidotos** [comment]
If someone wants to help to test new things for 0.4, in **master** can be found:

**Now Dock Plasmoid**
- drop launcher(s) for outside
- drop file(s) on a launcher to open it
- fix screen filtering
- set a task's activities (even though this is acting a little weird in my system and in plasma's icon taskmanager also)
- added new translation strings

**Now Dock Panel**
- two layouts (default and empty) after installation
- added new translation strings

**Comment by psifidotos** [comment]
one more for **Now Dock Panel** :)
- applets in the panel that are locked or can not be hovered (e.g. pagers and systemtray) gain a shadow by default

Do u think I should enable the user to choose if wants or not the above shadows?

**Comment by psifidotos** [comment]
and one more for **Now Dock Plasmoid** :)
- put lines and dots at the top instead of the bottom

**Comment by psifidotos** [comment]
there are some new strings in panel and plasmoid, sorry for the incovenience but the development was rapid today... :)

**Comment by psifidotos** [comment]
v0.4 which is compatible with Plasma 5.8 was released....
